apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtc-egress.fullname" . }}-api-server
  labels:
    {{- include "rtc-egress.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
    - port: {{ .Values.apiServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.apiServer.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "rtc-egress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-server