{{- if eq .Values.architecture "monolithic" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtc-egress.fullname" . }}
  labels:
    {{- include "rtc-egress.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rtc-egress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rtc-egress.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rtc-egress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry | default .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.apiPort }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.server.healthPort }}
              protocol: TCP
            # canvas port removed
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: REDIS_ADDR
              value: {{ .Values.redis.external.host }}:{{ .Values.redis.external.port }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.external.password | quote }}
            - name: REDIS_DB
              value: {{ .Values.redis.external.database | quote }}
            - name: GIN_MODE
              value: {{ .Values.server.ginMode | quote }}
            - name: API_PORT
              value: {{ .Values.server.apiPort | quote }}
            - name: HEALTH_PORT
              value: {{ .Values.server.healthPort | quote }}
            # CANVAS_TEMPLATE_PORT removed
            - name: LOG_LEVEL
              value: {{ .Values.server.logLevel | quote }}
            - name: POD_REGION
              value: {{ .Values.pod.region | quote }}
            - name: POD_WORKERS
              value: {{ .Values.pod.workers | quote }}
            - name: AGORA_APP_ID
              value: {{ .Values.agora.appId | quote }}
            - name: AGORA_ACCESS_TOKEN
              value: {{ .Values.agora.accessToken | quote }}
            - name: AGORA_CHANNEL_NAME
              value: {{ .Values.agora.channelName | quote }}
            - name: AGORA_EGRESS_UID
              value: {{ .Values.agora.egressUid | quote }}
            {{- if .Values.s3.enabled }}
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket | quote }}
            - name: S3_REGION
              value: {{ .Values.s3.region | quote }}
            - name: S3_ACCESS_KEY
              value: {{ .Values.s3.accessKey | quote }}
            - name: S3_SECRET_KEY
              value: {{ .Values.s3.secretKey | quote }}
            {{- if .Values.s3.endpoint }}
            - name: S3_ENDPOINT
              value: {{ .Values.s3.endpoint | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /opt/rtc_egress/config
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: recordings-storage
              mountPath: {{ .Values.persistence.recordings.mountPath }}
            - name: snapshots-storage
              mountPath: {{ .Values.persistence.snapshots.mountPath }}
            - name: logs-storage
              mountPath: {{ .Values.persistence.logs.mountPath }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "rtc-egress.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: recordings-storage
          persistentVolumeClaim:
            claimName: {{ include "rtc-egress.fullname" . }}-recordings
        - name: snapshots-storage
          persistentVolumeClaim:
            claimName: {{ include "rtc-egress.fullname" . }}-snapshots
        - name: logs-storage
          persistentVolumeClaim:
            claimName: {{ include "rtc-egress.fullname" . }}-logs
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
