{{- if eq .Values.architecture "separated" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtc-egress.fullname" . }}-uploader
  labels:
    {{- include "rtc-egress.labels" . | nindent 4 }}
    app.kubernetes.io/component: uploader
spec:
  replicas: {{ .Values.uploader.replicaCount }}
  selector:
    matchLabels:
      {{- include "rtc-egress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: uploader
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "rtc-egress.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: uploader
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rtc-egress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: uploader
          workingDir: "/"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry | default .Values.uploader.image.registry }}/{{ .Values.uploader.image.repository }}:{{ .Values.uploader.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.uploader.image.pullPolicy }}
          ports:
            - name: health
              containerPort: {{ .Values.uploader.service.healthPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.uploader.resources | nindent 12 }}
          env:
            - name: REDIS_ADDR
              value: {{ .Values.redis.external.host }}:{{ .Values.redis.external.port }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.external.password | quote }}
            - name: REDIS_DB
              value: {{ .Values.redis.external.database | quote }}
            - name: HEALTH_PORT
              value: {{ .Values.uploader.service.healthPort | quote }}
            - name: POD_REGION
              value: {{ .Values.pod.region | quote }}
            {{- if .Values.s3.enabled }}
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket | quote }}
            - name: S3_REGION
              value: {{ .Values.s3.region | quote }}
            - name: S3_ACCESS_KEY
              value: {{ .Values.s3.accessKey | quote }}
            - name: S3_SECRET_KEY
              value: {{ .Values.s3.secretKey | quote }}
            {{- if .Values.s3.endpoint }}
            - name: S3_ENDPOINT
              value: {{ .Values.s3.endpoint | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /opt/rtc_egress/config
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: recordings-storage
              mountPath: {{ .Values.persistence.recordings.mountPath }}
              readOnly: true
            - name: snapshots-storage
              mountPath: {{ .Values.persistence.snapshots.mountPath }}
              readOnly: true
            - name: logs-storage
              mountPath: {{ .Values.persistence.logs.mountPath }}
            {{- end }}
            {{- if .Values.uploader.webRecorder.createEmptyDir }}
            - name: web-recorder
              mountPath: {{ .Values.uploader.webRecorder.mountPath | default "/web_recorder" }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "rtc-egress.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: recordings-storage
          persistentVolumeClaim:
            claimName: {{ include "rtc-egress.fullname" . }}-recordings
        - name: snapshots-storage
          persistentVolumeClaim:
            claimName: {{ include "rtc-egress.fullname" . }}-snapshots
        - name: logs-storage
          persistentVolumeClaim:
            claimName: {{ include "rtc-egress.fullname" . }}-logs
        {{- end }}
        {{- if .Values.uploader.webRecorder.createEmptyDir }}
        - name: web-recorder
          emptyDir: {}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- end }}
